### PR TITLE
Updated the PRODUCT_NAME to match the new LineageOS

### PR DESCRIPTION
**Pull request by ruchernchong**

### CODE REVIEW

**Comment by IonKiwi** [comment]
lineage.mk overrides the product name:
PRODUCT_NAME := lineage_kccat6xx

changing it in full_kccat6xx.mk has no effect.

**Comment by ruchernchong** [comment]
screenshot_20170109-011329


Alright, since it has no effect, just letting you know that the build.prop currently on LineageOS is still showing this.

**Comment by IonKiwi** [comment]
thats strange, with lineage-14.1-20170107-UNOFFICIAL-kccat6xx.zip
screenshot_20170108-182101

**Comment by ruchernchong** [comment]
Okay, I will upgrade to the 2017017 build and report back to you.

**Comment by ruchernchong** [comment]
Fixed with lineage-20170108-UNOFFICIAL-kccat6xx build.

**Pull request closed without merging**
